# baseURL: 'https://www.superdan.pw/'
languageCode: 'zh-CN'
title: 'Dsiræ—¥è®°'
theme: 'hugo-theme-stack'
DefaultContentLanguage: zh-cn

languages:
    en:
        languageName: English
        title: Dsir website
        description: Example description
        weight: 2
    zh-cn:
        languageName: ä¸­æ–‡
        title: Dsiræ—¥è®°
        description: ä¸¹çš„ä¸ªäººç«™ç‚¹
        weight: 1
params:
    sidebar: 
        compact: false
        emoji: ğŸ¥
        subtitle: å•¦å•¦å•¦å•¦å•¦å•¦ï¼Œ
        avatar:
            enable: true
            src: img/avatar.jpg

    footer:
        since: 2023
        customText: 
    
    comments: 
        enabled: false
    widgets:


